### ISSUE TITLE
Error 500 if the language list is switched in the "Menu Headings".

### ISSUE THREAD

**Issue by max123kl** [ceford/j4xdemos-com-jdocmanual-v2#2]
### Steps to reproduce the issue
In the backend go to Components → JDOC Manual → Menu Headings
The function "Build Menus" should be executed already, if not do it now.
You will see a list as shown in the screenshot.
Then change the language in the marked box.

![Menu_Headings_List-en](https://github.com/ceford/j4xdemos-com-jdocmanual-v2/assets/853497/9febfeca-d52f-4ab6-aafd-e5b87576cb7e)

### Expected result
A new list of the selected language should appear

### Actual result
The following error message appears:
500 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS translation_id,(SELECT `c`.`display_title` FROM `hxbti_jdocmanual_menu_hea...' at line 1 

![Menu_Headings_List-ERROR](https://github.com/ceford/j4xdemos-com-jdocmanual-v2/assets/853497/ee0291c3-7cc9-464a-8ca8-96de221baa96)

If you switch back to the Dashboard as recommended and then back to "Menu Headings", the error page appears again.
Only after you log out and login again can you see the English list again.

### System information (as much as possible)
J4.3.3
PHP 8.1.21
10.5.19-MariaDB
Administrator Language English or German - same result

### Additional comments
With the announced extensive rebuild of the code, this bug might already be fixed. It should be checked.

**Comment by ceford** [comment]
I am about to upload a completely new implementation of the code. There are some additions to the data too. I am just working on the installation instructions. This version builds most of the database by reading the the md and txt files. More news soon.

**Comment by ceford** [comment]
Closing as I am archiving this repo. There is a new improved version.
